# 사용할 Node.js 이미지 지정 (클라이언트와 동일하게 22버전 사용)
FROM node:22-alpine

# 컨테이너 내부의 작업 디렉토리를 /app으로 설정합니다.
WORKDIR /app

# yarn.lock과 package.json 파일을 먼저 복사합니다.
COPY package.json ./
COPY yarn.lock ./

# yarn을 사용하여 의존성을 설치합니다.
RUN yarn install

# 나머지 모든 소스 코드를 컨테이너의 /app 디렉토리로 복사합니다.
COPY . .

# Express 서버가 5001번 포트에서 실행될 것이라고 Docker에게 알려줍니다.
EXPOSE 5001

# 컨테이너가 시작될 때 실행할 명령어입니다.
# package.json에 'dev' 스크립트가 있다면 해당 스크립트를 실행하는 것이 일반적입니다.
# 이 스크립트가 nodemon 등을 통해 코드 변경 시 서버를 자동 재시작하게 됩니다.
CMD ["yarn", "dev"]